version: '3'
services:
  frontend:
    build: ./client
    ports:
      - 3001:3000
    container_name: project-tag_frontend
    env_file:
      - ./client/.env
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - 5001:5000
    container_name: project-tag_backend
    env_file:
      - ./server/.env
    depends_on:
      - database

  database:
    image: postgres
    container_name: project-tag_database
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./server/.env

volumes:
  db_data:
