version: '3'
services:
  frontend:
    build: ./client
    ports:
      - 3000:3000
    container_name: bpchub_frontend
    env_file:
      - ./client/.env
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - 1337:1337
    container_name: bpchub_backend
    env_file:
      - ./server/.env
    depends_on:
      - database

  scrapper:
    build: ./server
    ports:
      - 5001:5000
    container_name: bpchub_scrapper
    env_file:
      - ./scrapper/.env
    depends_on:
      - backend

  database:
    image: postgres
    container_name: bpchub_database
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./database/.env

volumes:
  db_data:
