version: '3'
services:
  frontend:
    build:
      context: ./client
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm run build

  backend:
    build:
      context: ./server
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm run build

  scrapper:
    build:
      context: ./scrapper
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm run start:prod
